# Generated by Django 4.2.16 on 2024-09-25 22:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linux_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
